// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');
const casual = require('casual');
describe('Untitled', function () {
    this.timeout(30000);
    let driver;
    let vars;
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build();
        vars = {};
    });
    afterEach(async function () {
        await driver.quit();
    });
    it('history sales', async function () {
        await driver.get('http://localhost:3000/');
        await driver.manage().window().setRect(1200, 787);
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2020!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Bello Figo')]")), 5000);
        await driver.findElement(By.id('basic-nav-dropdown')).click();
        await driver.findElement(By.css('.dropdown-item:nth-child(2)')).click();
        assert(
            (await driver.findElement(By.css('tbody:nth-child(2) td:nth-child(2)')).getText()) === 'beautiful portrait',
        );
        assert((await driver.findElement(By.css('tbody:nth-child(2) td:nth-child(4)')).getText()) === '2021-02-26');
        await driver.sleep(4000);
    });
    /* it('create/buy product', async function () {
        const title = casual.title;
        const description = casual.short_description;
        const quantity = casual.integer(1, 200);
        const price = casual.integer(1, 50);
        await driver.get('http://localhost:3000/');
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello2@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2020!');
        await driver.findElement(By.css('.btn')).click();
        await driver.sleep(5000);
        await driver.findElement(By.xpath('//a[3]')).click();
        await driver.findElement(By.xpath('//input')).click();
        await driver.findElement(By.xpath('//input')).sendKeys(title);
        await driver.findElement(By.xpath('//span/input')).click();
        await driver.findElement(By.xpath('//span/input')).sendKeys(price);
        await driver.findElement(By.xpath('//div[3]/div[2]/span/input')).click();
        await driver.findElement(By.xpath('//div[3]/div[2]/span/input')).sendKeys(quantity);
        await driver.findElement(By.xpath('//div[2]/div/div/div')).click();
        await driver
            .findElement(By.xpath('/html/body/div/div/div[2]/div/div/div/form/div/div[4]/div[2]/div/div/div[1]/input'))
            .click();
        await driver.findElement(By.xpath('//div[2]/div/div/div[3]/div[2]')).click();
        await driver.findElement(By.xpath('//div[2]/div')).click();
        await driver.findElement(By.xpath('//div[6]/div[2]/div/div/div/input')).click();
        await driver.findElement(By.xpath('//th[2]')).click();
        await driver.findElement(By.xpath('//tr[2]/td[3]')).click(); //fallisce qui
        await driver.findElement(By.xpath('//tr[2]/td[5]')).click();
        await driver.findElement(By.xpath('//div[2]/div')).click();
        await driver.findElement(By.xpath('//div[7]/div[2]/div/div/div/input')).click();
        await driver.findElement(By.xpath('//div[7]/div[2]/div/div[2]/div/table/thead/tr/th[2]')).click();
        await driver.findElement(By.xpath('//table[2]/tbody/tr[3]/td[3]')).click();
        await driver.findElement(By.xpath('//div[7]/div[2]/div/div[2]/div/table/tbody/tr[2]/td[6]')).click();
        await driver.findElement(By.xpath('//div[2]/div')).click();
        await driver.findElement(By.xpath('//textarea')).click();
        await driver.findElement(By.xpath('//textarea')).sendKeys(description);
        await driver.findElement(By.xpath('//div[10]/a')).click();
        await driver.wait(
            until.elementLocated(By.xpath("//*[contains(text(), 'New Service/Product Submitted')]")),
            5000,
        );
        await driver.findElement(By.id('basic-nav-dropdown')).click();
        await driver.findElement(By.css('.dropdown-item:nth-child(5)')).click();
        await driver.findElement(By.xpath('/html/body/div/div/nav/div/div/div[2]/a[1]')).click();
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2021!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Bello Figo')]")), 5000);
        await await driver.findElement(By.css('.mx-3:nth-child(2)')).click();
        await driver.findElement(By.css('.col-lg-6:nth-child(3) .add')).click();
        await driver.findElement(By.css('.main-button')).click();
        await driver.findElement(By.id('basic-nav-dropdown')).click();
        await driver.findElement(By.css('.dropdown-item:nth-child(3)')).click();
        await driver.manage().window().setRect(1936, 1066);
    }); */
});
