// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

describe('landing check', function () {
    this.timeout(30000);
    let driver;
    let vars;
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build();
        vars = {};
    });
    afterEach(async function () {
        await driver.quit();
    });
    it('landing', async function () {
        await driver.get('http://localhost:3000/');
        await driver.manage().window().setRect(1440, 831);
        assert(
            (await driver.findElement(By.xpath("//strong[contains(.,'your journey')]")).getText()) === 'your journey',
        );
        assert(
            (await driver.findElement(By.xpath("//h5[contains(.,'Buy what you want')]")).getText()) ===
                'Buy what you want',
        );
        await driver.findElement(By.xpath('//div/div/div/div/div[2]')).click();
        assert(
            (await driver.findElement(By.xpath("//h6[contains(.,'About Raynholm It Dep')]")).getText()) ===
                'About Raynholm It Dep',
        );
    });
});
