// Generated by Selenium IDE
require('dotenv').config();
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');
const { text } = require('express');
const wrongResponse = 'Wrong email or password! Check them and retry';

describe('login', function () {
    this.timeout(30000);
    let driver;
    let vars;

    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build();
        vars = {};
    });
    afterEach(async function () {
        await driver.quit();
    });
    it('login ok', async function () {
        await driver.get('http://localhost:3000/');
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2020!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Bello Figo')]")), 5000);
        await driver.manage().window().setRect(1936, 1066);
    });

    it('login fail', async function () {
        await driver.get('http://localhost:3000/');
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2020i!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//*[contains(text(), '" + wrongResponse + "')]")), 2000);
        await driver.manage().window().setRect(1936, 1066);
    });
    it('login hack', async function () {
        await driver.get('http://localhost:3000/');
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys("Maga2020i!' or 1=1 --");
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//*[contains(text(), '" + wrongResponse + "')]")), 2000);
        await driver.manage().window().setRect(1936, 1066);
    });
});
