// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');
const absolutePath = '/Users/Vincenzo/Dropbox/UNIVERSITA/5^anno/CP/GitCp/CPProject2020/'; // change it for testing if you aren't Vincent :P
const relativeImgPathChild = 'backEnd/public/images/products/4571/051559a62744caf2f2c269338df3048a.jpeg';
const relativeImgPath = 'backEnd/public/images/products/default_image.png';

describe('change address', function () {
    this.timeout(30000);
    let driver;
    let vars;
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build();
        vars = {};
    });
    afterEach(async function () {
        await driver.quit();
    });
    it('change address', async function () {
        await driver.get('http://localhost:3000/');
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2020!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Bello Figo')]")), 5000);
        await driver.findElement(By.id('basic-nav-dropdown')).click();
        await driver.findElement(By.css('.dropdown-item:nth-child(1)')).click();
        await driver.sleep(4000);
        await driver.findElement(By.css('.btn-zena')).click();
        // await driver.findElement(By.name('address')).click();
        await driver.findElement(By.name('address')).clear();
        await driver.findElement(By.name('address')).sendKeys('Viale Dodecaneso 34, 10000, Genoa, GE');
        await driver.sleep(1500);
        await driver.findElement(By.css('.btn-zena')).click();
        // await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Edit profile with success!')]")), 3000);
        await driver.sleep(4000);
        {
            const value = await driver.findElement(By.name('address')).getAttribute('value');
            assert(value === 'Viale Dodecaneso 34, 10000, Genoa, GE');
        }
    });
    it('change password', async function () {
        await driver.get('http://localhost:3000/');
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2020!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Bello Figo')]")), 5000);
        await driver.findElement(By.id('basic-nav-dropdown')).click();
        await driver.findElement(By.css('.dropdown-item:nth-child(1)')).click();
        await driver.sleep(4000);
        await driver.findElement(By.css('.btn-zena')).click();
        await driver.findElement(By.name('password')).sendKeys('Maga2021!');
        await driver.findElement(By.name('confirmPassword')).sendKeys('Maga2021!');
        await driver.findElement(By.name('oldPassword')).sendKeys('Maga2020!');
        await driver.sleep(1500);
        await driver.findElement(By.css('.btn-zena')).click();
        await driver.sleep(4000);
        await driver.findElement(By.id('basic-nav-dropdown')).click();
        await driver.findElement(By.css('.dropdown-item:nth-child(5)')).click();
        await driver.findElement(By.xpath('/html/body/div/div/nav/div/div/div[2]/a[1]')).click();
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2021!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Bello Figo')]")), 5000);
    });
    it('rebase password', async function () {
        await driver.get('http://localhost:3000/');
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2021!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Bello Figo')]")), 5000);
        await driver.findElement(By.id('basic-nav-dropdown')).click();
        await driver.findElement(By.css('.dropdown-item:nth-child(1)')).click();
        await driver.sleep(4000);
        await driver.findElement(By.css('.btn-zena')).click();
        await driver.findElement(By.name('password')).sendKeys('Maga2020!');
        await driver.findElement(By.name('confirmPassword')).sendKeys('Maga2020!');
        await driver.findElement(By.name('oldPassword')).sendKeys('Maga2021!');
        await driver.sleep(1500);
        await driver.findElement(By.css('.btn-zena')).click();
    });
    it('remove image', async function () {
        await driver.get('http://localhost:3000/');
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2020!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Bello Figo')]")), 5000);
        await driver.findElement(By.id('basic-nav-dropdown')).click();
        await driver.findElement(By.css('.dropdown-item:nth-child(1)')).click();
        await driver.sleep(4000);
        await driver.findElement(By.css('.btn-zena')).click();
        await driver.findElement(By.css('.btn')).click();
        await driver.findElement(By.linkText('Remove Image')).click();
        await driver.findElement(By.css('.btn-zena')).click();
        await driver.sleep(4000);
        await driver.get('http://localhost:3000/myprofile');
        await driver.sleep(4000);
    });
    it('upload image', async function () {
        await driver.get('http://localhost:3000/');
        await driver.findElement(By.xpath("//a[contains(text(),'SignIn')]")).click();
        await driver.findElement(By.css('.mt-3 .form-control')).sendKeys('bello@figo.gu');
        await driver.findElement(By.name('password')).sendKeys('Maga2020!');
        await driver.findElement(By.css('.btn')).click();
        await driver.wait(until.elementLocated(By.xpath("//a[contains(text(),'Bello Figo')]")), 5000);
        await driver.findElement(By.id('basic-nav-dropdown')).click();
        await driver.findElement(By.css('.dropdown-item:nth-child(1)')).click();
        await driver.sleep(4000);
        await driver.findElement(By.css('.btn-zena')).click();
        await driver.findElement(By.css('.btn')).click();
        await driver.findElement(By.linkText('Upload New Image')).click();
        await driver.findElement(By.css('.chooseFileButton')).click();
        await driver.findElement(By.css('input:nth-child(5)')).sendKeys(absolutePath + relativeImgPathChild);
        await driver.findElement(By.css('.btn-zena')).click();
        await driver.sleep(4000);
        await driver.get('http://localhost:3000/myprofile');
        await driver.sleep(4000);
    });
});
