// Generated by Selenium IDE

const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');
const casual = require('casual');
require('../common_utils/casual');
describe('register', function () {
    this.timeout(30000);
    let driver;
    let vars;
    const firstname = casual.first_name;
    const surname = casual.last_name;
    const datebirth = casual.birthdate;
    const fiscalcode = casual.fiscal_code;
    const email = casual.email;
    const password = casual.password;
    const address = casual.address;
    const wrongResponse = 'An internal server error occurred';
    describe('ok', function () {
        it('registeration ok', async function () {
            await driver.get('http://localhost:3000');
            await driver.manage().window().setRect(1440, 831);
            await driver.findElement(By.xpath('/html/body/div/div/nav/div/div/div[3]/a[2]')).click();
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[1]/input'))
                .sendKeys(firstname);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[2]/input'))
                .sendKeys(surname);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[2]/div/input'))
                .sendKeys(datebirth);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[3]/div/input'))
                .sendKeys(fiscalcode);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[4]/div/input')).sendKeys(email);

            await driver
                .findElement(By.xpath('//html/body/div[3]/div/div/form/div/div[5]/div/input'))
                .sendKeys(password);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[6]/div/input'))
                .sendKeys(password);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[7]/div/input')).sendKeys(address);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[9]/input')).click();
            await driver.wait(
                until.elementLocated(By.xpath("//*[contains(text(), 'User registered with success!')]")),
                5000,
            );
        });

        it('registeration fail', async function () {
            await driver.get('http://localhost:3000');
            await driver.manage().window().setRect(1440, 831);
            await driver.findElement(By.xpath('/html/body/div/div/nav/div/div/div[3]/a[2]')).click();
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[1]/input'))
                .sendKeys(firstname);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[2]/input'))
                .sendKeys(surname);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[2]/div/input'))
                .sendKeys(datebirth);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[3]/div/input'))
                .sendKeys(fiscalcode);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[4]/div/input')).sendKeys(email);

            await driver
                .findElement(By.xpath('//html/body/div[3]/div/div/form/div/div[5]/div/input'))
                .sendKeys(password);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[6]/div/input'))
                .sendKeys(password);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[7]/div/input')).sendKeys(address);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[9]/input')).click();
            await driver.wait(until.elementLocated(By.xpath("//*[contains(text(), 'User already exists!')]")), 5000);
        });
        it('registeration hack surname', async function () {
            await driver.get('http://localhost:3000');
            await driver.manage().window().setRect(1440, 831);
            await driver.findElement(By.xpath('/html/body/div/div/nav/div/div/div[3]/a[2]')).click();
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[1]/input'))
                .sendKeys(firstname);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[2]/input'))
                .sendKeys(surname + "' or 1=1 --");
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[2]/div/input'))
                .sendKeys(datebirth);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[3]/div/input'))
                .sendKeys(fiscalcode);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[4]/div/input')).sendKeys(email);

            await driver
                .findElement(By.xpath('//html/body/div[3]/div/div/form/div/div[5]/div/input'))
                .sendKeys(password);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[6]/div/input'))
                .sendKeys(password);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[7]/div/input')).sendKeys(address);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[9]/input')).click();
            await driver.wait(until.elementLocated(By.xpath("//*[contains(text(), '" + wrongResponse + "')]")), 2000);
        });
        it('registeration hack firstname', async function () {
            await driver.get('http://localhost:3000');
            await driver.manage().window().setRect(1440, 831);
            await driver.findElement(By.xpath('/html/body/div/div/nav/div/div/div[3]/a[2]')).click();
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[1]/input'))
                .sendKeys(firstname + "' or 1=1 --");
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[2]/input'))
                .sendKeys(surname);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[2]/div/input'))
                .sendKeys(datebirth);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[3]/div/input'))
                .sendKeys(fiscalcode);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[4]/div/input')).sendKeys(email);

            await driver
                .findElement(By.xpath('//html/body/div[3]/div/div/form/div/div[5]/div/input'))
                .sendKeys(password);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[6]/div/input'))
                .sendKeys(password);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[7]/div/input')).sendKeys(address);
            await driver.findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[9]/input')).click();
            await driver.wait(until.elementLocated(By.xpath("//*[contains(text(), '" + wrongResponse + "')]")), 2000);
        });
        it('registeration wrong text', async function () {
            await driver.get('http://localhost:3000');
            await driver.manage().window().setRect(1440, 831);
            await driver.findElement(By.xpath('/html/body/div/div/nav/div/div/div[3]/a[2]')).click();
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[1]/input'))
                .sendKeys(firstname);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[1]/div[2]/input'))
                .sendKeys(surname);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[2]/div/input'))
                .sendKeys(datebirth);
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[3]/div/input'))
                .sendKeys(fiscalcode + 'p');
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[4]/div/input'))
                .sendKeys(email + '67');

            await driver
                .findElement(By.xpath('//html/body/div[3]/div/div/form/div/div[5]/div/input'))
                .sendKeys('sasa123456');
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[6]/div/input'))
                .sendKeys('sasa123456');
            await driver
                .findElement(By.xpath('/html/body/div[3]/div/div/form/div/div[7]/div/input'))
                .sendKeys('via del pifferaio magico 34');
            assert((await driver.findElement(By.xpath('//div[8]/div')).getText()) === 'Fiscal code not valid');
            assert((await driver.findElement(By.xpath('//div[8]/div[2]')).getText()) === 'Email not valid');
            assert(
                (await driver.findElement(By.xpath('//div[8]/div[3]')).getText()) ===
                    'Password MUST cointains: lowercase char, uppercase char, numbers and special char!',
            );
            assert(
                (await driver.findElement(By.xpath('//div[8]/div[4]')).getText()) ===
                    'Address not valid, es: Via Dodecaneso 35, 16146, Genoa, GE',
            );
        });
    });

    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build();
        vars = {};
    });
    afterEach(async function () {
        await driver.quit();
    });
});
