// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');
const casual = require('casual');
describe('history', function () {
    this.timeout(30000);
    let driver;
    let vars;
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build();
        vars = {};
    });
    afterEach(async function () {
        await driver.quit();
    });
    it('shopping', async function() {
        await driver.get("http://localhost:3000/")
        await driver.manage().window().setRect(1936, 1066)
        await driver.findElement(By.css(".navbar-nav:nth-child(3) > .mx-3:nth-child(1)")).click()
        await driver.findElement(By.css(".mt-3 .form-control")).click()
        await driver.findElement(By.css(".mt-3 .form-control")).sendKeys("bello@figo.gu")
        await driver.findElement(By.name("password")).click()
        await driver.findElement(By.name("password")).sendKeys("Maga2020!")
        await driver.findElement(By.css(".mx-3:nth-child(2)")).click()
        await driver.findElement(By.css(".col-lg-6:nth-child(5) .add")).click()
        await driver.findElement(By.css(".main-button")).click()
        await driver.findElement(By.id("basic-nav-dropdown")).click()
        await driver.findElement(By.css(".dropdown-item:nth-child(3)")).click()
        await driver.findElement(By.css("tbody:nth-child(10) td:nth-child(2)")).click()
        await driver.findElement(By.css("tbody:nth-child(10) td:nth-child(2)")).click()
        {
          const element = await driver.findElement(By.css("tbody:nth-child(10) td:nth-child(2)"))
          await driver.actions({ bridge: true}).doubleClick(element).perform()
        }
        assert(await driver.findElement(By.css("tbody:nth-child(10) td:nth-child(2)")).getText() == "Kittens")
        await driver.findElement(By.css(".btn")).click()
      })

      it('sales', async function() {
        await driver.get("http://localhost:3000/")
        await driver.manage().window().setRect(1936, 1066)
        await driver.findElement(By.css(".navbar-nav:nth-child(3) > .mx-3:nth-child(1)")).click()
        await driver.findElement(By.css(".mt-3 .form-control")).click()
        await driver.findElement(By.css(".mt-3 .form-control")).sendKeys("cptest@gmail.com")
        await driver.findElement(By.name("password")).click()
        await driver.findElement(By.name("password")).sendKeys("Test@1234")
        await driver.findElement(By.css(".btn")).click()
        await driver.findElement(By.css("svg")).click()
        await driver.findElement(By.css(".mx-3:nth-child(2)")).click()
        await driver.findElement(By.css(".col-lg-6:nth-child(2) .add")).click()
        await driver.findElement(By.css(".main-button")).click()
        await driver.findElement(By.id("basic-nav-dropdown")).click()
        await driver.findElement(By.css(".dropdown-item:nth-child(5)")).click()
        await driver.findElement(By.css(".navbar-nav:nth-child(3) > .mx-3:nth-child(1)")).click()
        await driver.findElement(By.css(".mt-3 .form-control")).click()
        await driver.findElement(By.css(".mt-3 .form-control")).sendKeys("bello@figo.gu")
        await driver.findElement(By.name("password")).click()
        await driver.findElement(By.name("password")).sendKeys("Maga2020!")
        await driver.findElement(By.css(".btn")).click()
        await driver.findElement(By.id("basic-nav-dropdown")).click()
        {
          const element = await driver.findElement(By.id("basic-nav-dropdown"))
          await driver.actions({ bridge: true }).moveToElement(element).perform()
        }
        {
          const element = await driver.findElement(By.CSS_SELECTOR, "body")
          await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
        }
        await driver.findElement(By.css(".dropdown-item:nth-child(2)")).click()
        await driver.findElement(By.css("tbody:nth-child(9) td:nth-child(2)")).click()
        await driver.findElement(By.css("tbody:nth-child(9) td:nth-child(2)")).click()
        {
          const element = await driver.findElement(By.css("tbody:nth-child(9) td:nth-child(2)"))
          await driver.actions({ bridge: true}).doubleClick(element).perform()
        }
        await driver.findElement(By.css("tbody:nth-child(9) td:nth-child(2)")).click()
        assert(await driver.findElement(By.css("tbody:nth-child(9) td:nth-child(2)")).getText() == "beautiful portrait")
      })
    })
    
    